sources:
  - name: BankDE
    path: BankDE_Domain.yaml
    behavior: domain

  - name: BankHK
    path: BankHK.yaml
    behavior: classical

  - name: BankUS
    url: https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/main/Bank/BankUS_Domain.yaml
    behavior: domain

  - name: BankSG
    url: https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/main/Bank/BankSG_Domain.yaml
    behavior: domain

  - name: BankUK
    path: BankUK.yaml
    behavior: classical

  - name: BrokerHK
    path: BrokerHK.yaml
    behavior: classical

  - name: BrokerUS
    path: BrokerUS.yaml
    behavior: classical

  - name: Wise
    url: https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/main/VirtualFinance/Wise.yaml
    behavior: classical

  - name: Revolut
    url: https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/main/VirtualFinance/Revolut.yaml
    behavior: classical

  - name: iFast
    path: iFast.yaml
    behavior: classical

  - name: CrackBypass
    path: Crack_Bypass_Domain.yaml
    behavior: domain

  - name: OtherBypass
    path: Other_Bypass_Domain.yaml
    behavior: domain
